SELECT TOP (1000) A.[IVR_SYSID]
      ,[PLN_SYSID]
      ,[ACT_SYSID]
      ,A.[USER_SYSID]
      ,[ADT_SYSID]
      ,[ADT_DATE]
      ,[ADT_ACTIVITY]
      ,[ADT_TABLE]
      ,[ADT_FIELD]
      ,[ADT_FIELD_TYPE]
      ,[ADT_BEFORE]
      ,[ADT_AFTER]
      ,[SUSER_NAME]
      --,[SYS_CD]
      --,[ORD_SYSID]
     -- ,[OTX_SYSID]
      --,[TRX_SYSID]
      ,B.[DLR_SYSID]
      ,B.[RGN_SYSID]
      ,B.[BRN_SYSID]
      ,B.[REP_SYSID]
      --,[MGT_SYSID]
  FROM [UVS].[adt] A
  LEFT JOIN [UVS].[ivr] B ON A.IVR_SYSID = B.IVR_SYSID
  LEFT JOIN [UVS].[rep] C ON B.REP_SYSID = C.REP_SYSID
  LEFT JOIN [UVS].[brn] D ON C.BRN_SYSID = D.BRN_SYSID
  WHERE [ADT_DATE] > '2025-08-31' AND [ADT_DATE] <= '2026-08-31'
  AND B.BRN_CD = 'ON010'
  AND ADT_AFTER IS NOT NULL AND ADT_AFTER <> ''
  AND A.ADT_FIELD <> 'USER_SYSID'
  AND A.ADT_FIELD NOT LIKE '%[_]DT%'
  AND A.ADT_FIELD NOT LIKE '%DATE%'
  AND ADT_TABLE IN ( 'KYC_PLN',
'PLN_COLLATERAL',
'IVR',
'CET_EFT',
'PLN_BENE',
'PLN',
'IVR_MKTG',
'CET_ADR',
'CET_FOREIGN_TAX',
'IVR_OWNER',
'KYC',
'CET_PHN',
'CET_FOREIGN_TAX_STATUS')
